apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),
    url(r'^$', CartInfoView.as_view(), name='show'),
    url(r'^update$', CartUpdateView.as_view(), name='update'),
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),
]

apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^detail/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),
    url(r'^list/(?P<type_id>\d)/(?P<page_index>\d)$', ListView.as_view(), name='list'),
]

apps/user/urls.py
from django.conf.urls import url
# from django.contrib.auth.decorators import login_required
from user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),  # /user/register 用户注册
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # /user/active 用户激活
    url(r'^login$', LoginView.as_view(), name='login'),  # /user/login 用户登录
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # /user/logout 用户退出
    url(r'^$', UserInfoView.as_view(), name='user'),  # /user 用户中心-首页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # /user/order 用户中心-首页
    url(r'^address$', AddressView.as_view(), name='address'),  # /user/address 用户中心-首页
]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search', include('haystack.urls')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^', include('goods.urls', namespace='goods')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin


# Create your views here.

class CartAddView(View):
    '''购物车记录添加'''

    def post(self, request):
        '''购物车记录添加'''

        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录！'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整！'})

        # 校验添加商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '添加数目出错！'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '添加的商品拍不存在！'})

        # 业务处理
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        ifadd = True  # 购物车商品数量是否增加 标识

        cart_count = conn.hget(cart_key, sku_id)  # 获取缓存中购物车商品数量
        if cart_count:
            count += int(cart_count)  # 累加购物车中商品数量
            ifadd = False

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足！'})

        conn.hset(cart_key, sku_id, count)  # 设置hash中sku_id的值
        total_count = conn.hlen(cart_key)  # 计算购物车商品数量

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count})


class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面'''

    def get(self, request):
        '''显示页面'''
        # 获取购物车数据
        user = request.user
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_info = conn.hgetall(cart_key)

        # 遍历缓存数据，生成页面数据
        skus = []
        total_count = 0
        total_amount = 0
        for sku_id, count in cart_info.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price * int(count)
            sku.count = count
            sku.amount = amount
            skus.append(sku)

            total_count += int(count)
            total_amount += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }

        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品id(sku_id) 更新的商品数量(count)
# /cart/update
class CartUpdateView(View):
    '''购物车记录更新'''
    def post(self, request):
        '''购物车记录更新'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理:更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4, 'errmsg':'商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':5, 'total_count':total_count, 'message':'更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品的id(sku_id)
# /cart/delete
class CartDeleteView(View):
    '''购物车记录删除'''
    def post(self, request):
        '''购物车记录删除'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'res':1, 'errmsg':'无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res':2, 'errmsg':'商品不存在'})

        # 业务处理:删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':3, 'total_count':total_count, 'message':'删除成功'})

templates/base.html
{# 首页、注册、登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容快 #}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href={% static "css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
    {# 网页引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block serarch_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src={% static "images/logo.png" %}></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock serarch_bar %}

{# 网页主题内容块 #}
{% block body %}{% endblock body %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

{# 网页底部html元素块 #}
{% block  bottom %}{% endblock bottom %}

{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页、列表页 #}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    {# 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心页面（3个） #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block pagetitle %}用户中心{% endblock pagetitle %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
            </ul>
        </div>

        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}

{% block main_content %}
    <div class="breadcrumb">
        <a href="{% url 'goods:list' 0 1 %}">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' sku.type.id 1 %}">{{ sku.type.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.desc }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unite }}</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>
            <div>
                <p>其他规格：</p>
                <ul>
                    {% for sku in same_spu_skus %}
                        <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                    {% empty %}
                        <li>无</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="total">总价：<em>元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart" sku_id= {{ sku.id }}>加入购物车</a>
                {% csrf_token %}
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ sku.goods.detail|safe }}</dd>
                </dl>
            </div>

            <div class="tab_content">
                <dl>
                    {% for order in sku_orders %}
                        <dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户：{{ order.order.user.username }}</dt>
                        <dd>评论内容：{{ order.comment }}</dd>
                    {% endfor %}
                </dl>
            </div>

        </div>
    </div>
{% endblock main_content %}

{% block bottom %}
    <div class="add_jump"></div>{% endblock bottom %}

{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        update_goods_amount()

        //计算商品总价
        function update_goods_amount() {
            price = parseFloat($('.show_pirze').children('em').text());
            count = parseInt($('.num_show').val());
            amount = price * count;
            $('.total').children('em').text(amount.toFixed(2) + '元');
        }

        //绑定+ - 商品数量事件
        $('.add').click(function () {
            count = parseInt($('.num_show').val());
            count++;
            $('.num_show').val(count);
            update_goods_amount();
        });

        $('.minus').click(function () {
            count = parseInt($('.num_show').val());
            if (count > 1) {
                count--;
                $('.num_show').val(count);
            }
            update_goods_amount();
        });

        //手动输入商品数量
        $('.num_show').blur(function () {
            count = $(this).val()
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) < 1) {
                count = 1;
            }

            $(this).val(parseInt(count));
            update_goods_amount();
        });

        //加入购物车
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $('#add_cart').click(function () {
            // ajax访问执行添加到购物车
            sku_id = $(this).attr('sku_id');
            count = $('.num_show').val();
            csrf = $('input[name="csrfmiddlewaretoken"]').val(); //配置csrf参数，防止post请求被阻挡
            params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf};

            $.post('/cart/add', params, function (data) {
                //重置红点位置
                $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
                if (data.res == 5) {
                    // 重置红点
                    $('.add_jump').offset().top = $add_x;
                    $('.add_jump').offset().left = $add_y;
                    // 添加成功，执行动画
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                //刷新购物车商品数量
                                $('#show_count').html(data.total_count);
                            });

                        });
                } else {
                    alert(data.errmsg);
                    $('.num_show').val(1);
                    update_goods_amount();
                }
            });
        })
    </script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-首页{% endblock title %}

{% block topfiles %}
    <script type="text/javascript" src={% static "js/jquery-1.12.4.min.js" %}></script>
    <script type="text/javascript" src={% static "js/jquery-ui.min.js" %}></script>
    <script type="text/javascript" src={% static "js/slide.js" %}></script>
{% endblock topfiles %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for banner in promotion_banners %}
                <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
        </div>
    </div>

    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for banner in type.title_banners %}
                        <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for banner in type.image_banners %}
                        <li>
                            <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                            <a href="{% url 'goods:detail' banner.sku.id %}"><img src={{ banner.sku.image.url }}></a>
                            <div class="prize">¥ {{ banner.sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}

{% block main_content %}
    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span><a href="#">{{ type.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="#">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list' type.id 1 %}?sort=defalut"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=hot"
                   {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in skus_page.object_list %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for pindex in pages.range %}
                    {% if pindex == skus_page.number %}
                        <a href="#" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页</a>
                {% endif %}bb
            </div>
        </div>
    </div>
{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-用户登录{% endblock title %}

{% block header_con %}{% endblock header_con %}
{% block serarch_bar %}{% endblock serarch_bar %}

{% block body %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src={% static "images/logo02.png" %}></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="/user/register">立即注册</a>
                </div>
                <div class="form_input">
                    {# 不设置表单Action，向浏览器当前地址提交表单 #}
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名"
                               value="{{ username }}">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="remember" {{ checked }}>
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">

                    </form>
                </div>
            </div>
        </div>
    </div>
    {{ errmsg }}
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}

{% block right_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user.username }}</li>
                <li><span>联系方式：</span>{{ address.phone }}</li>
                <li><span>联系地址：</span>{{ address.addr }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for sku in history_goods_skus %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% empty %}
                    <li>无浏览记录...</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock right_content %}